# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: HomeğŸ 
    url: '#about'
    weight: 10

  - name: BlogğŸ“
    url: "post/"
    weight: 20

  - name: ReportsğŸ“š
    url: "reports/"
    weight: 30

  - name: Scratch PadğŸ““
    url: "scratch_pad/"
    weight: 30

  - name: UtilitiesğŸ§°
    url: 'utilities/'
    weight: 40

  - name: PublicationsğŸ“ƒ
    url: 'publication/'
    weight: 50
    identifier : "publication"

  # - name: Conference Papers
  #   url: 'publication/#1'
  #   parent : "publication"

  # - name: Web Articles
  #   url: 'publication/#10'
  #   parent : "publication"

  # - name: Journal Article
  #   url: 'publication/#2'
  #   parent : "publication"

  # - name: Report
  #   url: 'publication/#4'
  #   parent : "publication"

  # - name: Thesis
  #   url: 'publication/#7'
  #   parent : "publication"

  # - name: Poster
  #   url: 'publication/#9'
  #   parent : "publication"

  - name: ContactğŸ“
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
